### ISSUE TITLE
CpMsgSetTime() macro does not work/ test failed

### ISSUE THREAD

**Issue by BergerMicroControl** [canpie/CANpie#20]
The CpMsgSetTime( ) functions in  CCF and FDF and FDM! are working fine, test passed.
But using macros in CCM the case fails with:
"TEST(CP_MSG_CCM, 005):FAIL: Expected 4 Was 0"
It seems that the will not be set by CpMsgSetTime( ) macro.

**Comment by microcontrol22** [comment]
The macro was missing, has been fixed with commit c3ca310.

**Comment by eacosta1976** [comment]
Hi Good morning.  My name is Edgar Acosta,  i work for DORC international in The Netherlands,  we are using CANPie in our solution.   I have a question,  do this change in CpMsgSetTime() function affects the end user of the library?.  i mean affects us in our design?.   

   Also, do you have a report of the issues detected in CANPie from clients whoi are using the library?.  

   I appreciate your help,  my email address is:     eacosta1976@gmail.com

**Comment by microcontrol22** [comment]
Hello,

the CANpie sources are maintained on Github:
https://github.com/canpie/CANpie <https://github.com/canpie/CANpie>

So can can put issues, change requests on the Gitbub page.


Best regards 
Uwe Koppe




            <http://www.microcontrol.net/produkte/steuerungen/umic200/>       	  <https://www.facebook.com/MicroControl.net>	  <https://plus.google.com/+MicroControlNet/posts>	  <https://twitter.com/MicroControl_DE>
  <http://www.microcontrol.net/>	
MicroControl GmbH & Co. KG
Junkersring 23
53844 Troisdorf, Germany

Fon: +49 (0)2241 / 256 59 - 0 
Fax: +49 (0)2241 / 256 59 - 11 
 

Persönlich haftend: MicroControl Systemhaus für Automatisierung Beteiligungsgesellschaft mbH,
Troisdorf, HRB 4952 Siegburg (GmbH), HRA 3110 Siegburg (KG), Ust-IdNr. DE812191199
Geschäftsführer: Dipl.-Ing. Uwe Koppe, Dipl.-Ing. (FH) Torsten Krahl, Dipl.-Ing. (FH) Frank Wielpütz
