### ISSUE TITLE
Makefile definition of ALL_CFILES

### ISSUE THREAD

**Issue by microcontrol22** [canpie/CANpie#22]
We should define the files which are taken into account by the symbol `ALL_CFILES`. So far, the 'ALL_CFILES' values was used to be the source for static code checking (e.g. splint). This means it only include files wich belong to the CANpie FD sources, but not the unit testing code (i.e. unity). If this is not the intention of `ALL_CFILES`, we need another symbol for the static code checker.

`ALL_CFILES = $(wildcard $(CAN_DIR)/*.c $(DEV_DIR)/*.c)`

**Comment by JoTid** [comment]
Maybe it is better to let the symbol `ALL_CFILES` as it was and add a new symbol like `ASTYLE_FILES` that defines all files that should be checked/modified by astyle. 
Additionally we can add another symbol for the static code checker, as proposed. That make it clear which files are used for what.

**Comment by microcontrol22** [comment]
Add new symbol `TEST_FILES` which defines all files that should be tested via MISRA-C and splint checker with revision 0904839.
