### ISSUE TITLE
Renaming of CP_MSG_FORMAT_MASK 

### ISSUE THREAD

**Issue by JoTid** [canpie/CANpie#24]
Should we rename the `CP_MSG_FORMAT_MASK` define to `CP_MASK_MSG_FORMAT` and put it in the  CP_MASK doxygen group:

<pre>
/*-------------------------------------------------------------------*/
/*!
** \def  CP_MASK_MSG_FORMAT
** \ingroup CP_MASK
**
** Mask for message format, used in combination with \c ubMsgCtrl field
** of the CpCanMsg_ts structure (CpCanMsg_s::ubMsgCtrl).
** This mask covers #CP_MSG_FORMAT_CBFF, #CP_MSG_FORMAT_CEFF,
** #CP_MSG_FORMAT_FBFF and #CP_MSG_FORMAT_FEFF control flags.
*/
#define  CP_MASK_MSG_FORMAT      ((uint8_t) 0x03)
</pre>

**Comment by microcontrol22** [comment]
Agreed. I will make the modifications in the `canpie.h` header and check it in.

**Comment by microcontrol22** [comment]
Solved with commit bc1c053.
