### ISSUE TITLE
Allow only one instance of 'CANpie Server' application

### ISSUE THREAD

**Issue by JoTid** [canpie/CANpie#35]
Only one instance of application should be allowed.

**Comment by eacosta1976** [comment]
HI.  this means that the Application that uses the CANPie driver shall be open only in one instance.  and if you try to open two instances there is a problem??… for example windows applications, you rise the first instance and you get access to CAN Bus... but if i try to reopen a second instance of the application, the second will not get access to CAN Bus?

**Comment by microcontrol22** [comment]
Solved by introduction of the QCanServerSettings class
