### ISSUE TITLE
CpCoreBitrate for classic CAN

### ISSUE THREAD

**Issue by mgiaco** [canpie/CANpie#5]
Hello,

For classic CAN there is only one baudrate parameter needed. So what is the correct usage here? 
Wouldn't it be better if you would differentiate this? 

Maybe this could be a solution.

```C
/*!
** \brief   Set bitrate of CAN controller
** \param   ptsPortV       Pointer to CAN port structure
** \param   slNomBitRateV  Nominal Bit Timing selection
** \param   slDatBitRateV  Data Bit Timing selection
**
** \return  Error code taken from the #CpErr_e enumeration. If no error
**          occurred, the function will return \c eCP_ERR_NONE.
*/
CpStatus_tv CpCoreBitrate(CpPort_ts *ptsPortV, int32_t slNomBitRateV,
                          int32_t slDatBitRateV);

#if CP_CAN_FD == 0
/*!
** \brief   Set baudrate of CAN controller
** \param   ptsPortV Pointer to CAN port structure
** \param   slBaudSelV baudrate selection
** \return  Error code taken from the #CpErr_e enumeration. If no error
**          occurred, the function will return \c eCP_ERR_NONE.
*/
#define CpCoreBaudrate(CH, A) CpCoreBitrate(CH, A, A)
#endif

```

**Comment by microcontrol22** [comment]
This is true, but the idea of the new CANpie version (aka CANpie FD) is to have only **one** set of functions for both, classic CAN and CAN FD. Hence some functions of the version 2 API are deprecated (or have additional parameters). 
Please think of the following application: a device needs to support CANopen and the upcoming CANopen FD protocol, the user selects the protocol via DIP-switch (or software). This means the CAN configuration (i.e. bit-rate setting) has to be done during run-time, not during compile-time.

**Comment by mgiaco** [comment]
Okay, and what do you think is the right way to call that? Should I do it that way ..
```C
	CpCoreBitrate(&can_port_main, eCP_BITRATE_250K, eCP_BITRATE_250K);
```

**Comment by microcontrol22** [comment]
If the data bit-rate is not required:

`CpCoreBitrate(&can_port_main, eCP_BITRATE_250K, eCP_BITRATE_NONE);`

**Comment by mgiaco** [comment]
Okay thanks.
