### ISSUE TITLE
CBFF, CEFF, FBFF, and FEFF

### ISSUE THREAD

**Issue by mgiaco** [canpie/CANpie#6]
What do these abbreviations mean exactly? So I know there is some documentation but I mean:
C... CAN ?
B... Bus?
F... ?
F... ?

**Comment by microcontrol22** [comment]
The documentation has been updated to clarify the abbreviations:
https://canpie.github.io/group__CP__MSG__CTRL.html#ga048baffc0f9875ee387bf4ad151d1f34

- CBFF: Classical base frame format
- CEFF: Classical extended frame format
- FBFF: FD base frame format
- FBFF: FD base frame format

The wording is taken from the actual specification ISO 11898-1:2015.

**Comment by mgiaco** [comment]
thanks
